### ISSUE TITLE
Implement selectable text that can be copied

### ISSUE THREAD

**Issue by MrToWy** [taylorh140/typst-pintora#1]
On [pintorajs.vercel.app](https://pintorajs.vercel.app) you can copy the text of a generated diagram.

![image](https://github.com/taylorh140/typst-pintora/assets/44198402/380ec583-c065-4188-b7e2-44c9b1fe39ae)

In [typst-pintora](https://github.com/taylorh140/typst-pintora), the text inside a diagram can not be copied.
Is is possible to implement selectable text in [typst-pintora](https://github.com/taylorh140/typst-pintora)?

**Comment by taylorh140** [comment]
Ahh im glad you ask since this should soon be possible without any effort on my end:
https://github.com/typst/typst/issues/1239

I asked for the same thing almost a year ago. The main details here is that the plugin produces SVGs and as implemented in typst they are not selectable. They depend on upstream libraries. Ill keep this open until it works though. 

Thanks for the issue.

**Comment by taylorh140** [comment]
This issue seems to be fixed upstream.
